spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/work
    username: wildfly
    password: KdUcyoPcYJ3JHDoRvXXw
